{
  "_annotation": {
    "cna": "github_m",
    "cve_id": "CVE-2024-22423",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-22423.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/yt-dlp/yt-dlp/commit/de015e930747165dbb8fcd360f8775fd973b7d6e",
      "https://github.com/yt-dlp/yt-dlp/commit/ff07792676f404ffff6ee61b5638c9dc1a33a37a",
      "https://github.com/yt-dlp/yt-dlp/releases/tag/2021.04.11",
      "https://github.com/yt-dlp/yt-dlp/releases/tag/2024.04.09",
      "https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-42h4-v29r-42qg",
      "https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-hjq6-52gw-2g7p",
      "https://www.kb.cert.org/vuls/id/123335"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:yt-dlp_project:yt-dlp:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "29896C7F-4789-5992-A27E-75EC113F388A",
                "versionEndExcluding": "2024.04.09",
                "versionStartIncluding": "2021.04.11",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}