{
  "_annotation": {
    "cve_id": "CVE-2024-49767",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-49767.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:palletsprojects:werkzeug:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "EF8FA717-D9DB-5736-BEA4-18744DB83DE1",
                "versionEndExcluding": "3.0.6",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      },
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:palletsprojects:quart:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "9E539F20-B2D2-42F4-98D4-DB92AAB1741E",
                "versionEndExcluding": "0.19.7",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}