{
  "_annotation": {
    "cve_id": "CVE-2024-26130",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "snapshot": "https://raw.githubusercontent.com/anchore/nvd-data-overrides/main/.snapshot/2024/CVE-2024-26130.json",
    "triage_notes": {
      "references": [
        "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4",
        "https://github.com/pyca/cryptography/pull/10423",
        "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55"
      ]
    }
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:cryptography_project:cryptography:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "3BE9E767-C146-433B-A470-75787F119110",
                "versionEndExcluding": "42.0.4",
                "versionStartIncluding": "38.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}