{
  "_annotation": {
    "cve_id": "CVE-2024-34711",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-34711.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:geoserver:geoserver:*:*:*:*:*:maven:*:*",
                "matchCriteriaId": "2E5C8AA2-D684-5B0F-9EFD-E80170EC6BCF",
                "versionEndExcluding": "2.25.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:org.geoserver:gs-main:*:*:*:*:*:maven:*:*",
                "matchCriteriaId": "36DEABEB-0022-5329-A137-C80E84B09562",
                "versionEndExcluding": "2.25.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:osgeo:geoserver:*:*:*:*:*:maven:*:*",
                "matchCriteriaId": "E38124A9-C98D-5450-A594-C3853AB99D6C",
                "versionEndExcluding": "2.25.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}