{
  "_annotation": {
    "cna": "github_m",
    "cve_id": "CVE-2024-35221",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-35221.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://en.wikipedia.org/wiki/Billion_laughs_attack",
      "https://github.com/ruby/ruby/blob/7cf74a2ff28b1b4c26e367d0d67521f7e1fed239/lib/rubygems/safe_yaml.rb#L28",
      "https://github.com/rubygems/rubygems.org/security/advisories/GHSA-4vc5-whwr-7hh2"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:rubygems:rubygems.org:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "986B5AAE-65F4-56D3-A4A3-12BF4424373A",
                "versionEndExcluding": "2024-04-12",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}