{
  "_annotation": {
    "cve_id": "CVE-2024-35195",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-35195.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:requests:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "7E00482A-D491-5CE3-91CB-B872299D699F",
                "versionEndExcluding": "2.32.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}