{
  "_annotation": {
    "cve_id": "CVE-2025-27696",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-27696.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:apache:superset:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "57872528-57EE-5B1D-AA27-B26FF7781933",
                "versionEndExcluding": "4.1.2",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}