{
  "_annotation": {
    "cve_id": "CVE-2025-57751",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-57751.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:pyload:pyload:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "F07C7972-B76E-5DCB-B4DD-569979E8690C",
                "versionEndExcluding": "0.5.0b3.dev92",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}