{
  "_annotation": {
    "cna": "go",
    "cve_id": "CVE-2025-47907",
    "description": "Cancelling a query (e.g. by cancelling the context passed to one of the query methods) during a call to the Scan method of the returned Rows can result in unexpected results if other queries are being made in parallel. This can result in a race condition that may overwrite the expected results with those of another query, causing the call to Scan to return either unexpected results from the other query or an error.",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-47907.json",
    "modified": "2025-08-07T15:48:03.634000+00:00",
    "published": "2025-08-07T15:25:30.704000+00:00",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://go.dev/cl/693735",
      "https://go.dev/issue/74831",
      "https://groups.google.com/g/golang-announce/c/x5MKroML2yM",
      "https://pkg.go.dev/vuln/GO-2025-3849"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "4F00F5D2-80E5-56DF-ADD9-B8325670E00D",
                "versionEndExcluding": "1.23.12",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:golang:go:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "61EF4510-ACEF-5B1C-B002-3DA0066C0D57",
                "versionEndExcluding": "1.24.6",
                "versionStartIncluding": "1.24.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}