{
  "_annotation": {
    "cve_id": "CVE-2025-32800",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-32800.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:anaconda:conda-build:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "70847E58-F725-5D1B-AB35-A37D8D642878",
                "versionEndExcluding": "25.3.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}