{
  "_annotation": {
    "cve_id": "CVE-2025-25295",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-25295.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:humansignal:label_studio:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "97CF995C-9861-5B00-8DC5-ECE5A0971DE3",
                "versionEndExcluding": "1.0.10",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}